### PR TITLE
Added search games functionality on the home screen

### PR DESCRIPTION
**Pull request by samitkapoor**
I have added the search games functionality on the home screen, the user will now be able to filter through the list of games when he submits on the keyboard and can revert back to scrolling the full list using the cross button on the textfield. I have made separate functions to implement the search bar. You may style the textfield any way you want, it is located in lib/widgets/search_widget.dart and the functions to filter the list are present in lib/screens/games_list_screen.dart.

### CODE REVIEW

**Comment by aryamangodara** [comment]
Cool ! 
I might merge after reviewing your PR

**Comment by aryamangodara** [comment]
> I have added the search games functionality on the home screen, the user will now be able to filter through the list of games when he submits on the keyboard and can revert back to scrolling the full list using the cross button on the textfield. I have made separate functions to implement the search bar. You may style the textfield any way you want, it is located in lib/widgets/search_widget.dart and the functions to filter the list are present in lib/screens/games_list_screen.dart.

can you implement it in the app bar of home screen ?

**Comment by samitkapoor** [comment]
@aryamangodara I have moved the searchbar in the appbar now. I have pushed the changes I made, kindly have a look!

**Comment by aryamangodara** [comment]
Good work !

**Pull request merged**
